server:
  servlet.session.cookie.name: CLIENTSESSIONID

logging:
  level:
    root: INFO

spring.security:
  oauth2:
    client:
      registration:
        oauth-demo-auth:
          client-id: oauth-client
          client-secret: noonewilleverguess
          authorization-grant-type: authorization_code
          redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
          scope: congratulation
          provider: oauth-demo-auth
      provider:
        oauth-demo-auth:
          authorization-uri: http://localhost:8082/oauth/authorize
          token-uri: http://localhost:8082/oauth/token
          user-info-uri: http://localhost:8082/user/me
          user-name-attribute: sub
